---
- name: Build the traefik bundle locally
  hosts: localhost
  tasks:
    - name: Build the traefik bundle
      include_role:
        name: traefik-build-bundle
      vars:
        http_port: 8880
        https_port: 8843
        dns_name: HOSTNAME_CHANGEME
        centralized_waf_url: http://arkime.12.berylia.org:4444
        backend_url: http://localhost
        enable_http: true
        enable_tls: true

- name: Deploy the traefik bundle to the webserver
  hosts: webserver
  tasks:
    - name: deploy traefik bundle
      include_role: 
        name: traefik-deploy-bundle
      vars:
        bundle_local_path: traefik_bundle.tar.gz
        unprivileged_user: www-data
        http_traefik_port: 8880
        https_traefik_port: 8843
