---
- name: Build the traefik bundle locally
  hosts: localhost
  tasks:
    - name: Build the traefik bundle
      include_role:
        name: traefik-build-bundle
      vars:
        traefik_version: 2.11.2
        arch: amd64

- name: Deploy the traefik bundle to the webserver
  hosts: webserver
  tasks:
    - name: deploy traefik bundle
      include_role: 
        name: traefik-deploy-bundle
      vars:
        centralized_waf_url: http://arkime.12.berylia.org:4444
        backend_url_http: http://localhost
        backend_url_https: https://localhost
        enable_http: true
        enable_tls: true
        unprivileged_user: www-data
        http_traefik_port: 8880
        https_traefik_port: 8843
        http_webserver_port: 80
        https_webserver_port: 443
        bundle_local_path: traefik_bundle.tar.gz
