---
traefik_version: 2.11.0
arch: amd64
http_port: 80
https_port: 443

dns_name: example.local
centralized_waf_url: http://ls24.wayren.ee:8000
backend_url: http://localhost:8080
enable_http: true
enable_tls: true
tls_crt_path: "files/certs/tls.crt"
tls_key_path: "files/certs/tls.key"
